### ISSUE TITLE
Issues about  extremely high dimension data

### ISSUE THREAD

**Issue by AckyZhang** [kwstat/hopkins#1]
By this definition Hopkins statistics will not be applicable to extremely high dimension data? like D = 4000+. This will result in either 0 or Not a Number ( Inf / Inf ).  

Or if this is used：
stat = 1 / (1 + sum(dwx^d) / sum( dux^d ) )
This will result in either 0 or 1.  （I’m not a English native so I didn't realize what 'it is not for our test cases' in the annotations means. Why this formula not used/usable?）

（I‘m trying to validate if there's clustering tendency in a questionaire with 102 items. Since the items plays the role being clustered, the 'dimension' here will be 4000+ subjects answering the questionaire....

So will it be fine if I repeat the process like 10000 repeats and count 1s and 0s？
Or is there any other clustering tendency index for this condition？

**Comment by kwstat** [comment]
I am having trouble understanding your post.
1. Can you create a reproducible example with simulated data that shows the problem that you see? Then explain your questions carefully. Assume that I know nothing about your problem.
2. Note that 1/ (1 + a/b) = 1/(b/b + a/b) = 1/( (b+a) /b ) = b/(b+a).
3. You need to explain in detail what your 102 questions represent. Are these numerical responses or categorical data?
4. I think you will find it very difficult to identify clusters in such high dimensions.  This is a problem with geometry (the curse of dimensionality). Perhaps you can perform PCA to reduce the dimensionality of your data.
5. 
 You may find some useful information here: https://www.quora.com/How-do-I-cluster-high-dimensional-data

**Comment by AckyZhang** [comment]
Thanks for your kindly reply. I guess you're right. Hopkins statistics is just not applicable for my problem.Sorry for bothering.
