### ISSUE TITLE
NaN or Error in numeric(3L^d) : vector size cannot be infinite, when using the hopkins method

### ISSUE THREAD

**Issue by FalsoMoralista** [kwstat/hopkins#2]
I don't know whether I am doing something wrong but here's what's happening:

I have a DataFrame in the format depicted below, which are features extracted from 15 images of a class (1024 dimensions).

```
[1] "Number of columns:"
[1] 1024
[1] "Data frame:"
# A tibble: 15 × 1,024
        n0      n1     n2     n3    n4      n5      n6       n7        n8    n9
     <dbl>   <dbl>  <dbl>  <dbl> <dbl>   <dbl>   <dbl>    <dbl>     <dbl> <dbl>
 1  0.160   0.0716 -0.259 0.176  0.517 -0.0688 -0.199   0.0999   0.156    0.384
 2 -0.100  -0.111  -0.294 0.305  0.373 -0.227  -0.130   0.553    0.128    0.313
 3  0.0758  0.0861 -0.276 0.196  0.595 -0.232  -0.0155 -0.0915  -0.000393 0.333
 4  0.164   0.0172 -0.189 0.173  0.354 -0.296  -0.0317  0.0504  -0.0319   0.355
 5  0.163  -0.107  -0.330 0.124  0.542 -0.296  -0.141  -0.00439 -0.0609   0.255
 6  0.296   0.0430 -0.400 0.186  0.606 -0.0735 -0.186   0.0813   0.206    0.465
 7  0.180  -0.0658 -0.266 0.193  0.344 -0.111   0.0569 -0.0170   0.105    0.356
 8  0.175   0.0847 -0.329 0.233  0.535 -0.180  -0.121  -0.0474   0.00945  0.400
 9  0.143   0.0531 -0.116 0.183  0.615 -0.246  -0.171   0.103   -0.0468   0.294
10  0.163  -0.121  -0.335 0.0410 0.802 -0.342  -0.0733 -0.149    0.0699   0.147
11  0.182   0.122  -0.264 0.239  0.571 -0.0713 -0.170  -0.0525   0.0392   0.313
12  0.290  -0.233  -0.283 0.115  0.508 -0.461  -0.0274 -0.194   -0.0963   0.272
13  0.154  -0.0282 -0.264 0.278  0.540 -0.0221 -0.225   0.141    0.205    0.293
14  0.134   0.132  -0.391 0.229  0.414 -0.172  -0.0504  0.295    0.226    0.277
15  0.107   0.0469 -0.235 0.157  0.590 -0.129  -0.0529  0.160    0.102    0.193
``` 
I then tried to run the hopkins as exemplified in the documentation: 
``` hopkins(test, m=2) ```
Which yields either ```NaN``` as ran as above or ```Error in numeric(3L^d) : vector size cannot be infinite```, when using torus geometry.

Another problem is when trying to set the number of samples equals to the number of rows (m=100%, i.e., 15), which outputs:   ```m must be no larger than num of samples``` (but it is actually equal, not greater then the number of samples).

**Comment by FalsoMoralista** [comment]
```R

library(conflicted)
library(reticulate)
library(hopkins)
library(readr)
library(tidyverse)

features <- read_csv('../features/ImageNET/inet_features.csv',show_col_types = FALSE)
features <- subset(features, select = -img_path) # Drop column

filter <- dplyr::filter

head(features, 10)

test <- features %>% filter( 
  class_id == 10003327 # Select one specific class from its ID
)

# drop other columns
test <- subset(test, select = -class_id)  # drop ids
test <- test[, -which(names(test) == "...1")] # drop index

print("Number of columns:")
ncol(test) # > 1024
print("Data frame:")
test
hopkins(test, m=2, method="torus") # > Error in numeric(3L^d) : vector size cannot be infinite

print("Hopkins iris dataset: ")
hopkins(iris[, -5], m=15) #  Work as expected (.9909486)
print("Gtruth: .9952293") 
```

**Comment by kwstat** [comment]
Your data has 1024 columns.  This is the dimension of the data.  The calculation of the statistic uses this:
```
hop <- sum(dux^d)/sum(dux^d + dwx^d)
```
If dux (distance between points) is any number other than 1, then dux^1024 will either be 0 or larger than floating point numbers can handle.

 It is impossible to work with such high-dimensional data. 

Also, m should be less than 10% of M.  See: https://github.com/kwstat/hopkins/blob/main/vignettes/hopkins_protocol.Rmd

**Comment by FalsoMoralista** [comment]
Thank you very much for the attention.

**Comment by FalsoMoralista** [comment]
What would be the implications of using lower values of d such as 1 or 2 (even though doesn't corresponds to the number of dimensions of my data i.e., 1024) from the point of view of assessing clusterability?

**Comment by kwstat** [comment]
The mathematical properties of Hopkins statistic are no longer valid.  See Figure 1 of https://journal.r-project.org/articles/RJ-2022-055/

**Comment by kwstat** [comment]
You seem desperate.  Here's something you might try--use PCA to reduce the dimension of your data down to 2 or 3.  If that captures most of the variation of the data, then you can try using Hopkins statistic.  If it does not capture most of the variation in the data, then I don't recommend this.
